import HwNavbar from "@/components/guest/hw-navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dua & Ruqyah",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#F7F8FA] flex w-full md:px-8 pt-8 px-4 lg:gap-5 overflow-hidden`}
      >
        <HwNavbar />
        {children}
      </body>
    </html>
  );
}
