import HwNavbar from "@/components/guest/hw-navbar";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

import SettingsTab from "@/components/guest/settings-tab";
import "./globals.css";
export const metadata: Metadata = {
  title: "Dua & Ruqyah",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-muted w-full h-[100vh] overflow-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex md:px-8 pt-8 px-4 lg:gap-5">
            <HwNavbar />
            {children}
            <div className="hidden 2xl:flex h-[90vh]">
              <SettingsTab />
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
